<?php
use Aheadworks\OneStepCheckout\Block\Adminhtml\System\Config\GeoIp\DownloadDatabase;
use Magento\Framework\Escaper;
use Aheadworks\OneStepCheckout\ViewModel\Serializer;

/**
 * @var DownloadDatabase $block
 * @var Escaper $escaper
 * @var Serializer $serializer
 */
$serializer = $block->getData('serializer');
?>
<?php
    $lastUpdated = $block->isDownloadedAndLibInstalled()
        ? $block->getLastUpdatedAt()
        : __('Never');
?>
<div class="aw-osc_button-container">
    <button class="action-default"
            type="button"
            data-role="download-geo-ip-database"
            <?php if ($block->isDisabled()): ?> disabled<?php endif; ?>
            data-mage-init='{"awOscDownloader": {
                "submitUrl": <?= /* @noEscape */ $serializer->serializeToJson($block->getSubmitUrl()) ?>,
                "fileName": <?= /* @noEscape */ $serializer->serializeToJson($block->getFileName()) ?>,
                "archiveName": <?= /* @noEscape */ $serializer->serializeToJson($block->getArchiveName()) ?>,
                "downloadedLabel": <?= /* @noEscape */ $serializer->serializeToJson($block->getButtonLabelDownloaded()) ?>,
                "isDownloaded": <?= /* @noEscape */ $serializer->serializeToJson($block->isDownloaded()) ?>,
                "linkedControlsSelector": <?= /* @noEscape */ $serializer->serializeToJson('#aw_osc_geo_ip_enabled') ?>,
                "noteTemplate": <?= /* @noEscape */ $serializer->serializeToJson(__('Last time updated: <%= updatedAt %>')) ?>
            }}'
            <?php if (!$block->isUpdateAvailable()): ?>
                <?php /* @noEscape */ echo 'disabled'?>
            <?php endif; ?>
    ><?php echo $escaper->escapeHtml($block->getButtonLabel()) ?></button>
</div>
<p class="note">
    <span data-role="download-geo-ip-updated-at"><?php echo $escaper->escapeHtml(__('Last time updated: %1', $lastUpdated)) ?></span>
</p>
<?php if ($block->isDownloadedAndLibInstalled()): ?>

<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#aw_osc_geo_ip_enabled": {
            "awOscInputEnabler": {
                "isEnabledInitial": <?= /* @noEscape */ $serializer->serializeToJson($block->isDownloadedAndLibInstalled()) ?>
            }
        }
    }
</script>
