<?php
/** @var $block \Aheadworks\OneStepCheckout\Block\Adminhtml\System\Config\DefaultValues\Region */

// @codingStandardsIgnoreFile
?>
<?php
    /** @var Magento\Framework\Data\Form\Element\AbstractElement $element */
    $element = $block->getElement();
    $element->setClass('input-text admin__control-text');
    $selectElementId = $element->getHtmlId() . '_id';
?>
<?= $element->getElementHtml() ?>
<select id="<?= $selectElementId ?>"
        name="<?= str_replace('region', 'region_id', $element->getName()) ?>"
        class="select admin__control-select">
    <option value=""><?= __('Please select a region, state or province.') ?></option>
</select>
<script type="text/x-magento-init">
    {
        "#<?= $block->getCountryIdElement()->getHtmlId() ?>": {
            "awOscRegionUpdater": {
                "optionalRegionAllowed": true,
                "isZipRequired": false,
                "isCountryRequired": false,
                "regionListId": "#<?= $selectElementId ?>",
                "regionInputId": "#<?= $element->getHtmlId() ?>",
                "form": "#form-validate",
                "regionJson": <?= $block->getRegionJson() ?>,
                "defaultRegion": "<?= $block->getRegionIdElement()->getValue()?>"
            }
        }
    }
</script>