<?php
/** @var $block \Aheadworks\OneStepCheckout\Block\Adminhtml\System\Config\CustomerInfo\Customization */

// @codingStandardsIgnoreFile
?>
<?php
    $htmlName = $block->getElement()->getName();
?>
<div class="aw-osc_fields-customization">
    <?php if ($block->isTopActionsBlockVisible()) :?>
        <div class="top-actions">
            <div class="action-wrap">
                <button type="button"
                        class="action-default action-add-attribute"
                        onclick="window.location.href = '<?= $block->escapeHtmlAttr($block->getNewCustomerAttributeLink()) ?>'">
                    <span><?= $block->escapeHtml(__('Add a Customer Attribute')) ?></span>
                </button>
            </div>
        </div>
    <?php endif; ?>

    <div class="aw-osc_customization-note"><?php echo $block->escapeHtml(__('Define field names and drag and drop them to required position.')) ?></div>
    <div>
        <table class="admin__control-table" data-mage-init='{"awOscDraggableFieldArray": {}}'>
            <tbody data-role="row-container">
            <?php foreach ($block->getAttrCodesGroupedByFieldRow() as $fieldRowId => $attrCodes): ?>
                <tr>
                    <td class="col-draggable">
                        <?php
                        $sortOrder = $block->getFieldRowSortOrder($fieldRowId);
                        ?>
                        <div data-role="draggable-handle" class="draggable-handle"
                             title="<?php echo $block->escapeHtml(__('Sort Rows')) ?>"></div>
                        <input
                            data-role="sort-order"
                            type="hidden"
                            name="<?php /* @noEscape */ echo $htmlName ?>[rows][<?php /* @noEscape */ echo $fieldRowId ?>][sort_order]"
                            value="<?php /* @noEscape */ echo $sortOrder ?>"/>
                    </td>
                    <td class="col-attributes">
                        <?php foreach ($attrCodes as $attrCode): ?>
                            <?php
                                $defaultValues = $block->getAttributeFormDefaultValues($attrCode);
                                $formValues = $block->getAttributeFormValues($attrCode, $defaultValues);
                                $label = $formValues['label'];
                                $defaultLabel = $defaultValues['label'];
                                $visible = $formValues['visible'];
                                $required = $formValues['required'];
                            ?>
                            <div class="attribute-item-<?php /* @noEscape */ echo $attrCode ?>" data-mage-init='{"awOscAttributeMetaEdit": {}}'>
                                <label class="item-label<?php if ($required): ?> required-mark<?php endif; ?>"
                                       for="<?php /* @noEscape */ echo $block->getInputHtmlId($attrCode, 'label') ?>"></label>
                                <input id="<?php /* @noEscape */ echo $block->getInputHtmlId($attrCode, 'label') ?>"
                                       name="<?php /* @noEscape */ echo $block->getInputHtmlName($attrCode, 'label', null, '__outer') ?>"
                                       value="<?php /* @noEscape */ echo $label ?>"
                                       placeholder="<?php /* @noEscape */ echo $defaultLabel ?>"
                                       class="input-text required-entry"
                                       type="text"
                                    <?php if (!$visible): ?> disabled="disabled" <?php endif; ?>
                                       data-required="<?php if ($required): ?>1<?php else: ?>0<?php endif; ?>"
                                       data-meta-field-name="label"/>
                                <input data-value-input-id="<?php /* @noEscape */ echo $block->getInputHtmlId($attrCode, 'label') ?>"
                                       type="hidden"
                                       name="<?php /* @noEscape */ echo $block->getInputHtmlName($attrCode, 'label') ?>"
                                       value="<?php /* @noEscape */ echo $label ?>"/>
                                <div class="edit-actions">
                                    <?php foreach ($block->getBooleanMetaFields() as $metaField => $inputLabel): ?>
                                        <?php
                                        $metaValue = $formValues[$metaField] ? 1 : 0;
                                        ?>
                                        <input type="checkbox"
                                               name="<?php /* @noEscape */ echo $block->getInputHtmlName($attrCode, $metaField, null, '__outer') ?>]"
                                               value="1"
                                               id="<?php /* @noEscape */ echo $block->getInputHtmlId($attrCode, $metaField) ?>"
                                            <?php if ($metaValue): ?>
                                                checked="checked"
                                            <?php endif; ?>
                                               data-meta-field-name="<?php /* @noEscape */ echo $metaField ?>"/>
                                        <label for="<?php /* @noEscape */ echo $block->getInputHtmlId($attrCode, $metaField) ?>" class="label">
                                            <span><?php echo $block->escapeHtml(__($inputLabel)) ?></span>
                                        </label>
                                        <input data-value-input-id="<?php /* @noEscape */ echo $block->getInputHtmlId($attrCode, $metaField) ?>"
                                               type="hidden"
                                               name="<?php /* @noEscape */ echo $block->getInputHtmlName($attrCode, $metaField) ?>]"
                                               value="<?php /* @noEscape */ echo $metaValue ?>"/>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
