<?php
use Aheadworks\OneStepCheckout\Block\Adminhtml\System\Config\TrustSeals\Badges;
use Magento\Framework\Escaper;
use Aheadworks\OneStepCheckout\ViewModel\Serializer;

// @codingStandardsIgnoreFile

/**
 * @var Badges $block
 * @var Escaper $escaper
 * @var Serializer $serializer
 */
$serializer = $block->getData('serializer');
?>
<?php
    $htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
    $colSpan = $block->isAddAfter() ? 2 : 1;
?>
<div class="aw-osc_field-array aw-osc_trust-seals" id="grid<?php /* @noEscape */ echo $htmlId ?>">
    <script id="aw-osc_trust-seals_template" data-role="row-template" type="text/x-magento-template">
        <tr id="<%- _id %>" data-role="row">
            <?php foreach ($block->getColumns() as $columnName => $column): ?>
                <td><?php /* @noEscape */ echo $block->renderCellTemplate($columnName) ?></td>
                <?php if ($block->isAddAfter()): ?>
                    <td>
                        <button class="action-add"
                                type="button"
                                data-role="add-after-button">
                            <span><?php echo $escaper->escapeHtml(__('Add after')) ?></span>
                        </button>
                    </td>
                <?php endif; ?>
            <?php endforeach; ?>
            <td class="col-actions">
                <button class="action-delete"
                        type="button"
                        data-role="delete-button"
                        data-row-id="<%- _id %>">
                    <span><?php echo $escaper->escapeHtml(__('Delete')) ?></span>
                </button>
            </td>
        </tr>
    </script>
    <div class="admin__control-table-wrapper">
        <table class="admin__control-table" data-mage-init='{"awOscFieldArray": {
            "defaultRowData": <?= /* @noEscape */ $serializer->serializeToJson($block->getDefaultRowData()) ?>,
            "rows": <?= /* @noEscape */ $serializer->serializeToJson($block->getRows()) ?>,
            "template": "#aw-osc_trust-seals_template",
            "maxRows": 3
        }}'>
            <thead>
            <tr>
                <?php foreach ($block->getColumns() as $columnName => $column): ?>
                    <th><?php echo $escaper->escapeHtml($column['label']) ?></th>
                <?php endforeach; ?>
                <th class="col-actions" colspan="<?php /* @noEscape */ echo $colSpan ?>"><?php echo $escaper->escapeHtml(__('Action')) ?></th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <td colspan="<?php /* @noEscape */ echo count($block->getColumns()) + $colSpan ?>" class="col-actions-add">
                    <button  class="action-add"
                             title="<?php echo $escaper->escapeHtml(__('Add')) ?>"
                             type="button"
                             data-role="add-button"
                    >
                        <span><?php echo $escaper->escapeHtml(__('Add')) ?></span>
                    </button>
                </td>
            </tr>
            </tfoot>
            <tbody data-role="rows-container"></tbody>
        </table>
    </div>
    <input type="hidden" name="<?php /* @noEscape */ echo $block->getElement()->getName(); ?>[__empty]" value="" />
    <?php if ($block->getElement()->getDisabled()): ?>
        <script>
            require(
                [
                    'rjsResolver'
                ], function(resolver) {
                    resolver(() => {
                            toggleValueElements({checked: true}, $('grid<?= $escaper->escapeJs($htmlId)?>').parentNode);
                        }
                    );
                });
        </script>
    <?php endif; ?>
</div>
